#!/data/data/com.termux/files/usr/bin/python3
import colorama
from colorama import Fore
colorama.init(autoreset=True)
from countryinfo import CountryInfo

c = input("Enter country: ").title()

country = CountryInfo(c)
#print(dir(country))

data = country.alt_spellings()
data1 = country.capital()
data2 = country.capital_latlng()
data3 = country.calling_codes()
data4 = country.area()
data5 = country.population()
data6 = country.borders()
data7 = country.currencies()
data8 = country.languages()
data10 = country.demonym()
data11 = country.flag()
data12 = country.geo_json()
data13 = country.iso()
data14 = country.latlng()
data15 = country.name()
data16 = country.native_name()
data17 = country.provinces()
data18 = country.region()
data19 = country.subregion()
data20 = country.timezones()
data21 = country.tld()
data22 = country.translations()
data23 = country.wiki()

print(f"{Fore.GREEN}Speelings:",data)
print(f"{Fore.GREEN}Capital:",data1)
print(f"{Fore.GREEN}Capital's lat,lon:",data2)
print(f"{Fore.GREEN}Calling code:",data3)
print(f"{Fore.GREEN}Area:",data4)
print(f"{Fore.GREEN}Population:",data5)
print(f"{Fore.GREEN}Border counteies:",data6)
print(f"{Fore.GREEN}Currencies:",data7)
print(f"{Fore.GREEN}Languages:",data8)
print(f"{Fore.GREEN}Demonym:",data10)
print(f"{Fore.GREEN}flag:",data11)
print(f"{Fore.GREEN}Geograpy:",data12['features'][0]['id'],",",data12['features'][0]['properties']['name'],",",data12['features'][0]['geometry']['type'])
print(f"{Fore.GREEN}Iso:",data13)
print(f"{Fore.GREEN}Latitude, Longitude:",data14)
print(f"{Fore.GREEN}Name:",data15)
print(f"{Fore.GREEN}Native name:",data16)
print(f"{Fore.GREEN}Provinces:",len(data17),"\n",data17)
print(f"{Fore.GREEN}Region:",data18)
print(f"{Fore.GREEN}Sub-region:",data19)
print(f"{Fore.GREEN}Timezone:",data20)
print(f"{Fore.GREEN}Tld:",data21)
print(f"{Fore.GREEN}Translations:",data22)
print(f"{Fore.GREEN}Visit wikipedia:",data23)

